#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace WcfService.Repositories
{
	using Telerik.OpenAccess;
	using DataLayer;
	using System;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Collections;
	using System.Collections.Generic;
	using System.Runtime.Serialization;

	
	public partial interface IRepository<TEntity>
	{
	    void Add(TEntity entity);
	    void Remove(TEntity entity);
	
	    TEntity Get(ObjectKey objectKey);
	    
	    IQueryable<TEntity> GetAll();
	
	    IQueryable<TEntity> Find(Expression<Func<TEntity, bool>> predicate);
	}
	
	public partial class Repository<TEntity> : IRepository<TEntity>
	        where TEntity : class
	{
	    protected IUnitOfWork unitOfWork;
	
	    public Repository(IUnitOfWork unitOfWork)
	    {
	        this.unitOfWork = unitOfWork;
	    }
	
	    public void Add(TEntity entity)
	    {
			this.unitOfWork.Add(entity);
	    }
	
	    public void Remove(TEntity entity)
	    {
	        this.unitOfWork.Delete(entity);
	    }
	
	    public IQueryable<TEntity> GetAll()
	    {
	        return this.unitOfWork.GetAll<TEntity>();
	    }
	
	    public TEntity Get(ObjectKey objectKey)
	    {
	        return this.unitOfWork.GetObjectByKey<TEntity>(objectKey);
	    }
	
	    public IQueryable<TEntity> Find(Expression<Func<TEntity, bool>> predicate)
	    {
	        return this.unitOfWork.GetAll<TEntity>().Where(predicate);
	    }
	}
	
	public partial interface IStudioCommercialeRepository : IRepository<StudioCommerciale>
	{ 
	
	}
	
	public partial class StudioCommercialeRepository : Repository<StudioCommerciale>, IStudioCommercialeRepository
	{
	    public StudioCommercialeRepository(IEntitiesModelUnitOfWork unitOfWork)
	        : base(unitOfWork)
	    {
	    }
	}
	
	public partial interface IAziendaRepository : IRepository<Azienda>
	{ 
	
	}
	
	public partial class AziendaRepository : Repository<Azienda>, IAziendaRepository
	{
	    public AziendaRepository(IEntitiesModelUnitOfWork unitOfWork)
	        : base(unitOfWork)
	    {
	    }
	}
	
	public partial interface IContabilitaRepository : IRepository<Contabilita>
	{ 
	
	}
	
	public partial class ContabilitaRepository : Repository<Contabilita>, IContabilitaRepository
	{
	    public ContabilitaRepository(IEntitiesModelUnitOfWork unitOfWork)
	        : base(unitOfWork)
	    {
	    }
	}
	
	public partial interface IComunicazioneRepository : IRepository<Comunicazione>
	{ 
	
	}
	
	public partial class ComunicazioneRepository : Repository<Comunicazione>, IComunicazioneRepository
	{
	    public ComunicazioneRepository(IEntitiesModelUnitOfWork unitOfWork)
	        : base(unitOfWork)
	    {
	    }
	}
	
	public partial interface IDocumentoRepository : IRepository<Documento>
	{ 
	
	}
	
	public partial class DocumentoRepository : Repository<Documento>, IDocumentoRepository
	{
	    public DocumentoRepository(IEntitiesModelUnitOfWork unitOfWork)
	        : base(unitOfWork)
	    {
	    }
	}
	
	public partial interface IAccountRepository : IRepository<Account>
	{ 
	
	}
	
	public partial class AccountRepository : Repository<Account>, IAccountRepository
	{
	    public AccountRepository(IEntitiesModelUnitOfWork unitOfWork)
	        : base(unitOfWork)
	    {
	    }
	}
	
	public partial interface IImportRepository : IRepository<Import>
	{ 
	
	}
	
	public partial class ImportRepository : Repository<Import>, IImportRepository
	{
	    public ImportRepository(IEntitiesModelUnitOfWork unitOfWork)
	        : base(unitOfWork)
	    {
	    }
	}
	
	public partial interface IExportRepository : IRepository<Export>
	{ 
	
	}
	
	public partial class ExportRepository : Repository<Export>, IExportRepository
	{
	    public ExportRepository(IEntitiesModelUnitOfWork unitOfWork)
	        : base(unitOfWork)
	    {
	    }
	}
	
	public partial interface IAnagraficaAziendaRepository : IRepository<AnagraficaAzienda>
	{ 
	
	}
	
	public partial class AnagraficaAziendaRepository : Repository<AnagraficaAzienda>, IAnagraficaAziendaRepository
	{
	    public AnagraficaAziendaRepository(IEntitiesModelUnitOfWork unitOfWork)
	        : base(unitOfWork)
	    {
	    }
	}
	
	public partial interface IClienteRepository : IRepository<Cliente>
	{ 
	
	}
	
	public partial class ClienteRepository : Repository<Cliente>, IClienteRepository
	{
	    public ClienteRepository(IEntitiesModelUnitOfWork unitOfWork)
	        : base(unitOfWork)
	    {
	    }
	}
	
	public partial interface ICustomerRepository : IRepository<Customer>
	{ 
	
	}
	
	public partial class CustomerRepository : Repository<Customer>, ICustomerRepository
	{
	    public CustomerRepository(IEntitiesModelUnitOfWork unitOfWork)
	        : base(unitOfWork)
	    {
	    }
	}
}
#pragma warning restore 1591
