#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DataLayer;
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace WcfService.Dto
{
	public interface IDtoWithKey
	{
		string DtoKey { get; set; }
	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(AccountDto))]
	[KnownType(typeof(AziendaDto))]
	[KnownType(typeof(NominativoDto))]
	public partial class StudioCommercialeDto : IDtoWithKey
	{
		public StudioCommercialeDto()
		{
		}
		
		public StudioCommercialeDto(int _id, string _denominazione, string _tipoSoftwareContabilita, IList<AccountDto> _accounts, IList<AziendaDto> _aziendas, IList<NominativoDto> _nominativos)
		{
			this.Id = _id;
			this.Denominazione = _denominazione;
			this.TipoSoftwareContabilita = _tipoSoftwareContabilita;
			this.Accounts = _accounts;
			this.Aziendas = _aziendas;
			this.Nominativos = _nominativos;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual string Denominazione { get;set; }

		[DataMember]
		public virtual string TipoSoftwareContabilita { get;set; }

		[DataMember]
		public virtual IList<AccountDto> Accounts { get;set; }

		[DataMember]
		public virtual IList<AziendaDto> Aziendas { get;set; }

		[DataMember]
		public virtual IList<NominativoDto> Nominativos { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(StudioCommercialeDto))]
	[KnownType(typeof(AccountDto))]
	[KnownType(typeof(ContabilitaDto))]
	[KnownType(typeof(ClienteDto))]
	public partial class AziendaDto : IDtoWithKey
	{
		public AziendaDto()
		{
		}
		
		public AziendaDto(int _id, string _tipoContabilita, string _tipoSoftwareFatturazione, string _iDAzienda, string _iDConto, string _coficeFiscale, string _partitaIVA, string _ragioneSociale, string _indirizzo, string _cap, string _comune, string _provincia, string _email, string _telefono, string _fax, int _studioCommercialeId, StudioCommercialeDto _studioCommerciale, IList<AccountDto> _accounts, IList<ContabilitaDto> _contabilitas, IList<ClienteDto> _clientes)
		{
			this.Id = _id;
			this.TipoContabilita = _tipoContabilita;
			this.TipoSoftwareFatturazione = _tipoSoftwareFatturazione;
			this.IDAzienda = _iDAzienda;
			this.IDConto = _iDConto;
			this.CoficeFiscale = _coficeFiscale;
			this.PartitaIVA = _partitaIVA;
			this.RagioneSociale = _ragioneSociale;
			this.Indirizzo = _indirizzo;
			this.Cap = _cap;
			this.Comune = _comune;
			this.Provincia = _provincia;
			this.Email = _email;
			this.Telefono = _telefono;
			this.Fax = _fax;
			this.StudioCommercialeId = _studioCommercialeId;
			this.StudioCommerciale = _studioCommerciale;
			this.Accounts = _accounts;
			this.Contabilitas = _contabilitas;
			this.Clientes = _clientes;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual string TipoContabilita { get;set; }

		[DataMember]
		public virtual string TipoSoftwareFatturazione { get;set; }

		[DataMember]
		public virtual string IDAzienda { get;set; }

		[DataMember]
		public virtual string IDConto { get;set; }

		[DataMember]
		public virtual string CoficeFiscale { get;set; }

		[DataMember]
		public virtual string PartitaIVA { get;set; }

		[DataMember]
		public virtual string RagioneSociale { get;set; }

		[DataMember]
		public virtual string Indirizzo { get;set; }

		[DataMember]
		public virtual string Cap { get;set; }

		[DataMember]
		public virtual string Comune { get;set; }

		[DataMember]
		public virtual string Provincia { get;set; }

		[DataMember]
		public virtual string Email { get;set; }

		[DataMember]
		public virtual string Telefono { get;set; }

		[DataMember]
		public virtual string Fax { get;set; }

		[DataMember]
		public virtual int StudioCommercialeId { get;set; }

		[DataMember]
		public virtual StudioCommercialeDto StudioCommerciale { get;set; }

		[DataMember]
		public virtual IList<AccountDto> Accounts { get;set; }

		[DataMember]
		public virtual IList<ContabilitaDto> Contabilitas { get;set; }

		[DataMember]
		public virtual IList<ClienteDto> Clientes { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(AziendaDto))]
	[KnownType(typeof(ComunicazioneDto))]
	public partial class ContabilitaDto : IDtoWithKey
	{
		public ContabilitaDto()
		{
		}
		
		public ContabilitaDto(int _id, string _anno, string _tipo, int _aziendaId, AziendaDto _azienda, IList<ComunicazioneDto> _comunicaziones)
		{
			this.Id = _id;
			this.Anno = _anno;
			this.Tipo = _tipo;
			this.AziendaId = _aziendaId;
			this.Azienda = _azienda;
			this.Comunicaziones = _comunicaziones;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual string Anno { get;set; }

		[DataMember]
		public virtual string Tipo { get;set; }

		[DataMember]
		public virtual int AziendaId { get;set; }

		[DataMember]
		public virtual AziendaDto Azienda { get;set; }

		[DataMember]
		public virtual IList<ComunicazioneDto> Comunicaziones { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(ContabilitaDto))]
	[KnownType(typeof(ExportDto))]
	public partial class ComunicazioneDto : IDtoWithKey
	{
		public ComunicazioneDto()
		{
		}
		
		public ComunicazioneDto(int _id, int _contabilitaId, string _numero, DateTime _scadenzaIVA, ContabilitaDto _contabilita, IList<ExportDto> _exports)
		{
			this.Id = _id;
			this.ContabilitaId = _contabilitaId;
			this.Numero = _numero;
			this.ScadenzaIVA = _scadenzaIVA;
			this.Contabilita = _contabilita;
			this.Exports = _exports;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int ContabilitaId { get;set; }

		[DataMember]
		public virtual string Numero { get;set; }

		[DataMember]
		public virtual DateTime ScadenzaIVA { get;set; }

		[DataMember]
		public virtual ContabilitaDto Contabilita { get;set; }

		[DataMember]
		public virtual IList<ExportDto> Exports { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(ExportDto))]
	public partial class DocumentoDto : IDtoWithKey
	{
		public DocumentoDto()
		{
		}
		
		public DocumentoDto(int _id, string _iDCliente, int _exportId, string _partitaIVA, string _tipo, DateTime _data, string _iDMovimento, string _iDCausale, string _iDConto, string _iDRegistroIVA, string _iDIVA, decimal _importo, decimal _imponibileIVA, decimal _importoIVA, string _tipoRiga, ExportDto _export)
		{
			this.Id = _id;
			this.IDCliente = _iDCliente;
			this.ExportId = _exportId;
			this.PartitaIVA = _partitaIVA;
			this.Tipo = _tipo;
			this.Data = _data;
			this.IDMovimento = _iDMovimento;
			this.IDCausale = _iDCausale;
			this.IDConto = _iDConto;
			this.IDRegistroIVA = _iDRegistroIVA;
			this.IDIVA = _iDIVA;
			this.Importo = _importo;
			this.ImponibileIVA = _imponibileIVA;
			this.ImportoIVA = _importoIVA;
			this.TipoRiga = _tipoRiga;
			this.Export = _export;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual string IDCliente { get;set; }

		[DataMember]
		public virtual int ExportId { get;set; }

		[DataMember]
		public virtual string PartitaIVA { get;set; }

		[DataMember]
		public virtual string Tipo { get;set; }

		[DataMember]
		public virtual DateTime Data { get;set; }

		[DataMember]
		public virtual string IDMovimento { get;set; }

		[DataMember]
		public virtual string IDCausale { get;set; }

		[DataMember]
		public virtual string IDConto { get;set; }

		[DataMember]
		public virtual string IDRegistroIVA { get;set; }

		[DataMember]
		public virtual string IDIVA { get;set; }

		[DataMember]
		public virtual decimal Importo { get;set; }

		[DataMember]
		public virtual decimal ImponibileIVA { get;set; }

		[DataMember]
		public virtual decimal ImportoIVA { get;set; }

		[DataMember]
		public virtual string TipoRiga { get;set; }

		[DataMember]
		public virtual ExportDto Export { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(StudioCommercialeDto))]
	[KnownType(typeof(AziendaDto))]
	public partial class AccountDto : IDtoWithKey
	{
		public AccountDto()
		{
		}
		
		public AccountDto(int _id, int _studioCommercialeId, int _aziendaId, string _username, string _password, string _nickname, StudioCommercialeDto _studioCommerciale, AziendaDto _azienda)
		{
			this.Id = _id;
			this.StudioCommercialeId = _studioCommercialeId;
			this.AziendaId = _aziendaId;
			this.Username = _username;
			this.Password = _password;
			this.Nickname = _nickname;
			this.StudioCommerciale = _studioCommerciale;
			this.Azienda = _azienda;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int StudioCommercialeId { get;set; }

		[DataMember]
		public virtual int AziendaId { get;set; }

		[DataMember]
		public virtual string Username { get;set; }

		[DataMember]
		public virtual string Password { get;set; }

		[DataMember]
		public virtual string Nickname { get;set; }

		[DataMember]
		public virtual StudioCommercialeDto StudioCommerciale { get;set; }

		[DataMember]
		public virtual AziendaDto Azienda { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(ExportDto))]
	public partial class ImportDto : IDtoWithKey
	{
		public ImportDto()
		{
		}
		
		public ImportDto(int _id, string _tipoRiga, string _iDIVA, DateTime _data, string _tXTMovimenti, string _tXTClienti, ExportDto _export)
		{
			this.Id = _id;
			this.TipoRiga = _tipoRiga;
			this.IDIVA = _iDIVA;
			this.Data = _data;
			this.TXTMovimenti = _tXTMovimenti;
			this.TXTClienti = _tXTClienti;
			this.Export = _export;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual string TipoRiga { get;set; }

		[DataMember]
		public virtual string IDIVA { get;set; }

		[DataMember]
		public virtual DateTime Data { get;set; }

		[DataMember]
		public virtual string TXTMovimenti { get;set; }

		[DataMember]
		public virtual string TXTClienti { get;set; }

		[DataMember]
		public virtual ExportDto Export { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(ComunicazioneDto))]
	[KnownType(typeof(DocumentoDto))]
	[KnownType(typeof(ImportDto))]
	public partial class ExportDto : IDtoWithKey
	{
		public ExportDto()
		{
		}
		
		public ExportDto(int _id, int _comunicazioneId, DateTime _data, string _progressivo, string _xmlFile, ComunicazioneDto _comunicazione, IList<DocumentoDto> _documentos, ImportDto _import)
		{
			this.Id = _id;
			this.ComunicazioneId = _comunicazioneId;
			this.Data = _data;
			this.Progressivo = _progressivo;
			this.XmlFile = _xmlFile;
			this.Comunicazione = _comunicazione;
			this.Documentos = _documentos;
			this.Import = _import;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int ComunicazioneId { get;set; }

		[DataMember]
		public virtual DateTime Data { get;set; }

		[DataMember]
		public virtual string Progressivo { get;set; }

		[DataMember]
		public virtual string XmlFile { get;set; }

		[DataMember]
		public virtual ComunicazioneDto Comunicazione { get;set; }

		[DataMember]
		public virtual IList<DocumentoDto> Documentos { get;set; }

		[DataMember]
		public virtual ImportDto Import { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(StudioCommercialeDto))]
	public partial class NominativoDto : IDtoWithKey
	{
		public NominativoDto()
		{
		}
		
		public NominativoDto(int _id, int _studioCommercialeId, string _ragioneSociale, string _iDNominativo, string _codiceFiscale, string _partitaIVA, string _indirizzo, string _comune, string _provincia, string _email, string _telefono, string _fax, StudioCommercialeDto _studioCommerciale)
		{
			this.Id = _id;
			this.StudioCommercialeId = _studioCommercialeId;
			this.RagioneSociale = _ragioneSociale;
			this.IDNominativo = _iDNominativo;
			this.CodiceFiscale = _codiceFiscale;
			this.PartitaIVA = _partitaIVA;
			this.Indirizzo = _indirizzo;
			this.Comune = _comune;
			this.Provincia = _provincia;
			this.Email = _email;
			this.Telefono = _telefono;
			this.Fax = _fax;
			this.StudioCommerciale = _studioCommerciale;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int StudioCommercialeId { get;set; }

		[DataMember]
		public virtual string RagioneSociale { get;set; }

		[DataMember]
		public virtual string IDNominativo { get;set; }

		[DataMember]
		public virtual string CodiceFiscale { get;set; }

		[DataMember]
		public virtual string PartitaIVA { get;set; }

		[DataMember]
		public virtual string Indirizzo { get;set; }

		[DataMember]
		public virtual string Comune { get;set; }

		[DataMember]
		public virtual string Provincia { get;set; }

		[DataMember]
		public virtual string Email { get;set; }

		[DataMember]
		public virtual string Telefono { get;set; }

		[DataMember]
		public virtual string Fax { get;set; }

		[DataMember]
		public virtual StudioCommercialeDto StudioCommerciale { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(AziendaDto))]
	public partial class ClienteDto : IDtoWithKey
	{
		public ClienteDto()
		{
		}
		
		public ClienteDto(int _id, int _aziendaId, string _iDConto, string _iDNominativo, AziendaDto _azienda)
		{
			this.Id = _id;
			this.AziendaId = _aziendaId;
			this.IDConto = _iDConto;
			this.IDNominativo = _iDNominativo;
			this.Azienda = _azienda;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int AziendaId { get;set; }

		[DataMember]
		public virtual string IDConto { get;set; }

		[DataMember]
		public virtual string IDNominativo { get;set; }

		[DataMember]
		public virtual AziendaDto Azienda { get;set; }

	}
	
}
#pragma warning restore 1591
