#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class Azienda
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _tipoContabilita;
		public virtual string TipoContabilita
		{
			get
			{
				return this._tipoContabilita;
			}
			set
			{
				this._tipoContabilita = value;
			}
		}
		
		private string _tipoSoftwareFatturazione;
		public virtual string TipoSoftwareFatturazione
		{
			get
			{
				return this._tipoSoftwareFatturazione;
			}
			set
			{
				this._tipoSoftwareFatturazione = value;
			}
		}
		
		private string _iDAzienda;
		public virtual string IDAzienda
		{
			get
			{
				return this._iDAzienda;
			}
			set
			{
				this._iDAzienda = value;
			}
		}
		
		private int _studioCommercialeId;
		public virtual int StudioCommercialeId
		{
			get
			{
				return this._studioCommercialeId;
			}
			set
			{
				this._studioCommercialeId = value;
			}
		}
		
		private int _anagraficaAziendaId;
		public virtual int AnagraficaAziendaId
		{
			get
			{
				return this._anagraficaAziendaId;
			}
			set
			{
				this._anagraficaAziendaId = value;
			}
		}
		
		private string _mdbFile;
		public virtual string MdbFile
		{
			get
			{
				return this._mdbFile;
			}
			set
			{
				this._mdbFile = value;
			}
		}
		
		private DateTime? _ultimoAggiornamento;
		public virtual DateTime? UltimoAggiornamento
		{
			get
			{
				return this._ultimoAggiornamento;
			}
			set
			{
				this._ultimoAggiornamento = value;
			}
		}
		
		private StudioCommerciale _studioCommerciale;
		public virtual StudioCommerciale StudioCommerciale
		{
			get
			{
				return this._studioCommerciale;
			}
			set
			{
				this._studioCommerciale = value;
			}
		}
		
		private AnagraficaAzienda _anagraficaAzienda;
		public virtual AnagraficaAzienda AnagraficaAzienda
		{
			get
			{
				return this._anagraficaAzienda;
			}
			set
			{
				this._anagraficaAzienda = value;
			}
		}
		
		private IList<Account> _accounts = new List<Account>();
		public virtual IList<Account> Accounts
		{
			get
			{
				return this._accounts;
			}
		}
		
		private IList<Contabilita> _contabilitas = new List<Contabilita>();
		public virtual IList<Contabilita> Contabilitas
		{
			get
			{
				return this._contabilitas;
			}
		}
		
		private IList<Cliente> _clientes = new List<Cliente>();
		public virtual IList<Cliente> Clientes
		{
			get
			{
				return this._clientes;
			}
		}
		
	}
}
#pragma warning restore 1591
