#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class Cliente
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _aziendaId;
		public virtual int AziendaId
		{
			get
			{
				return this._aziendaId;
			}
			set
			{
				this._aziendaId = value;
			}
		}
		
		private string _iDCliente;
		public virtual string IDCliente
		{
			get
			{
				return this._iDCliente;
			}
			set
			{
				this._iDCliente = value;
			}
		}
		
		private int _anagraficaAziendaId;
		public virtual int AnagraficaAziendaId
		{
			get
			{
				return this._anagraficaAziendaId;
			}
			set
			{
				this._anagraficaAziendaId = value;
			}
		}
		
		private string _iDConto;
		public virtual string IDConto
		{
			get
			{
				return this._iDConto;
			}
			set
			{
				this._iDConto = value;
			}
		}
		
		private Azienda _azienda;
		public virtual Azienda Azienda
		{
			get
			{
				return this._azienda;
			}
			set
			{
				this._azienda = value;
			}
		}
		
		private AnagraficaAzienda _anagraficaAzienda;
		public virtual AnagraficaAzienda AnagraficaAzienda
		{
			get
			{
				return this._anagraficaAzienda;
			}
			set
			{
				this._anagraficaAzienda = value;
			}
		}
		
	}
}
#pragma warning restore 1591
