#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class Cliente
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _studioCommercialeId;
		public virtual int StudioCommercialeId
		{
			get
			{
				return this._studioCommercialeId;
			}
			set
			{
				this._studioCommercialeId = value;
			}
		}
		
		private string _tipoContabilita;
		public virtual string TipoContabilita
		{
			get
			{
				return this._tipoContabilita;
			}
			set
			{
				this._tipoContabilita = value;
			}
		}
		
		private string _tipoSoftwareFatturazione;
		public virtual string TipoSoftwareFatturazione
		{
			get
			{
				return this._tipoSoftwareFatturazione;
			}
			set
			{
				this._tipoSoftwareFatturazione = value;
			}
		}
		
		private string _codiceCliente;
		public virtual string CodiceCliente
		{
			get
			{
				return this._codiceCliente;
			}
			set
			{
				this._codiceCliente = value;
			}
		}
		
		private string _iDContro;
		public virtual string IDContro
		{
			get
			{
				return this._iDContro;
			}
			set
			{
				this._iDContro = value;
			}
		}
		
		private StudioCommerciale _studioCommerciale;
		public virtual StudioCommerciale StudioCommerciale
		{
			get
			{
				return this._studioCommerciale;
			}
			set
			{
				this._studioCommerciale = value;
			}
		}
		
		private IList<Contabilita> _contabilitas = new List<Contabilita>();
		public virtual IList<Contabilita> Contabilitas
		{
			get
			{
				return this._contabilitas;
			}
		}
		
		private IList<Account> _accounts = new List<Account>();
		public virtual IList<Account> Accounts
		{
			get
			{
				return this._accounts;
			}
		}
		
	}
}
#pragma warning restore 1591
