#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class Comunicazione
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _contabilitaId;
		public virtual int ContabilitaId
		{
			get
			{
				return this._contabilitaId;
			}
			set
			{
				this._contabilitaId = value;
			}
		}
		
		private string _xmlExportFile;
		public virtual string XmlExportFile
		{
			get
			{
				return this._xmlExportFile;
			}
			set
			{
				this._xmlExportFile = value;
			}
		}
		
		private string _xmlImportFile;
		public virtual string XmlImportFile
		{
			get
			{
				return this._xmlImportFile;
			}
			set
			{
				this._xmlImportFile = value;
			}
		}
		
		private Contabilita _contabilita;
		public virtual Contabilita Contabilita
		{
			get
			{
				return this._contabilita;
			}
			set
			{
				this._contabilita = value;
			}
		}
		
		private IList<Fattura> _fatturas = new List<Fattura>();
		public virtual IList<Fattura> Fatturas
		{
			get
			{
				return this._fatturas;
			}
		}
		
		private IList<Import> _imports = new List<Import>();
		public virtual IList<Import> Imports
		{
			get
			{
				return this._imports;
			}
		}
		
	}
}
#pragma warning restore 1591
