#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class Comunicazione
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _contabilitaId;
		public virtual int ContabilitaId
		{
			get
			{
				return this._contabilitaId;
			}
			set
			{
				this._contabilitaId = value;
			}
		}
		
		private string _numero;
		public virtual string Numero
		{
			get
			{
				return this._numero;
			}
			set
			{
				this._numero = value;
			}
		}
		
		private DateTime? _scadenzaIVA;
		public virtual DateTime? ScadenzaIVA
		{
			get
			{
				return this._scadenzaIVA;
			}
			set
			{
				this._scadenzaIVA = value;
			}
		}
		
		private Contabilita _contabilita;
		public virtual Contabilita Contabilita
		{
			get
			{
				return this._contabilita;
			}
			set
			{
				this._contabilita = value;
			}
		}
		
		private IList<Export> _exports = new List<Export>();
		public virtual IList<Export> Exports
		{
			get
			{
				return this._exports;
			}
		}
		
	}
}
#pragma warning restore 1591
