#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class Contabilita
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _anno;
		public virtual string Anno
		{
			get
			{
				return this._anno;
			}
			set
			{
				this._anno = value;
			}
		}
		
		private string _scadenzaIVA;
		public virtual string ScadenzaIVA
		{
			get
			{
				return this._scadenzaIVA;
			}
			set
			{
				this._scadenzaIVA = value;
			}
		}
		
		private int _clienteId;
		public virtual int ClienteId
		{
			get
			{
				return this._clienteId;
			}
			set
			{
				this._clienteId = value;
			}
		}
		
		private Cliente _cliente;
		public virtual Cliente Cliente
		{
			get
			{
				return this._cliente;
			}
			set
			{
				this._cliente = value;
			}
		}
		
		private IList<Comunicazione> _comunicaziones = new List<Comunicazione>();
		public virtual IList<Comunicazione> Comunicaziones
		{
			get
			{
				return this._comunicaziones;
			}
		}
		
	}
}
#pragma warning restore 1591
