#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class EntitiesModel : OpenAccessContext, IEntitiesModelUnitOfWork
	{
		private static string connectionStringName = @"ESIEFiscaleConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntitiesModel.rlinq");
		
		public EntitiesModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public EntitiesModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public EntitiesModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public EntitiesModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public EntitiesModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<StudioCommerciale> StudioCommerciales 
		{
			get
			{
				return this.GetAll<StudioCommerciale>();
			}
		}
		
		public IQueryable<Azienda> Aziendas 
		{
			get
			{
				return this.GetAll<Azienda>();
			}
		}
		
		public IQueryable<Contabilita> Contabilitas 
		{
			get
			{
				return this.GetAll<Contabilita>();
			}
		}
		
		public IQueryable<Comunicazione> Comunicaziones 
		{
			get
			{
				return this.GetAll<Comunicazione>();
			}
		}
		
		public IQueryable<Documento> Documentos 
		{
			get
			{
				return this.GetAll<Documento>();
			}
		}
		
		public IQueryable<Account> Accounts 
		{
			get
			{
				return this.GetAll<Account>();
			}
		}
		
		public IQueryable<Import> Imports 
		{
			get
			{
				return this.GetAll<Import>();
			}
		}
		
		public IQueryable<Export> Exports 
		{
			get
			{
				return this.GetAll<Export>();
			}
		}
		
		public IQueryable<AnagraficaAzienda> AnagraficaAziendas 
		{
			get
			{
				return this.GetAll<AnagraficaAzienda>();
			}
		}
		
		public IQueryable<Cliente> Clientes 
		{
			get
			{
				return this.GetAll<Cliente>();
			}
		}
		
		public IQueryable<Customer> Customers 
		{
			get
			{
				return this.GetAll<Customer>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MsSql";
			backend.ProviderName = "System.Data.SqlClient";
			backend.Logging.MetricStoreSnapshotInterval = 0;
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of EntitiesModel.
		/// </summary>
		/// <param name="config">The BackendConfiguration of EntitiesModel.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IEntitiesModelUnitOfWork : IUnitOfWork
	{
		IQueryable<StudioCommerciale> StudioCommerciales
		{
			get;
		}
		IQueryable<Azienda> Aziendas
		{
			get;
		}
		IQueryable<Contabilita> Contabilitas
		{
			get;
		}
		IQueryable<Comunicazione> Comunicaziones
		{
			get;
		}
		IQueryable<Documento> Documentos
		{
			get;
		}
		IQueryable<Account> Accounts
		{
			get;
		}
		IQueryable<Import> Imports
		{
			get;
		}
		IQueryable<Export> Exports
		{
			get;
		}
		IQueryable<AnagraficaAzienda> AnagraficaAziendas
		{
			get;
		}
		IQueryable<Cliente> Clientes
		{
			get;
		}
		IQueryable<Customer> Customers
		{
			get;
		}
	}
}
#pragma warning restore 1591
