#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class Fattura
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _comunicazioneId;
		public virtual int ComunicazioneId
		{
			get
			{
				return this._comunicazioneId;
			}
			set
			{
				this._comunicazioneId = value;
			}
		}
		
		private string _codiceFornitore;
		public virtual string CodiceFornitore
		{
			get
			{
				return this._codiceFornitore;
			}
			set
			{
				this._codiceFornitore = value;
			}
		}
		
		private Comunicazione _comunicazione;
		public virtual Comunicazione Comunicazione
		{
			get
			{
				return this._comunicazione;
			}
			set
			{
				this._comunicazione = value;
			}
		}
		
		private IList<Import> _imports = new List<Import>();
		public virtual IList<Import> Imports
		{
			get
			{
				return this._imports;
			}
		}
		
	}
}
#pragma warning restore 1591
