#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class Nominativo
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _studioCommercialeId;
		public virtual int StudioCommercialeId
		{
			get
			{
				return this._studioCommercialeId;
			}
			set
			{
				this._studioCommercialeId = value;
			}
		}
		
		private string _ragioneSociale;
		public virtual string RagioneSociale
		{
			get
			{
				return this._ragioneSociale;
			}
			set
			{
				this._ragioneSociale = value;
			}
		}
		
		private string _iDNominativo;
		public virtual string IDNominativo
		{
			get
			{
				return this._iDNominativo;
			}
			set
			{
				this._iDNominativo = value;
			}
		}
		
		private string _codiceFiscale;
		public virtual string CodiceFiscale
		{
			get
			{
				return this._codiceFiscale;
			}
			set
			{
				this._codiceFiscale = value;
			}
		}
		
		private string _partitaIVA;
		public virtual string PartitaIVA
		{
			get
			{
				return this._partitaIVA;
			}
			set
			{
				this._partitaIVA = value;
			}
		}
		
		private string _indirizzo;
		public virtual string Indirizzo
		{
			get
			{
				return this._indirizzo;
			}
			set
			{
				this._indirizzo = value;
			}
		}
		
		private string _comune;
		public virtual string Comune
		{
			get
			{
				return this._comune;
			}
			set
			{
				this._comune = value;
			}
		}
		
		private string _provincia;
		public virtual string Provincia
		{
			get
			{
				return this._provincia;
			}
			set
			{
				this._provincia = value;
			}
		}
		
		private string _email;
		public virtual string Email
		{
			get
			{
				return this._email;
			}
			set
			{
				this._email = value;
			}
		}
		
		private string _telefono;
		public virtual string Telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				this._telefono = value;
			}
		}
		
		private string _fax;
		public virtual string Fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				this._fax = value;
			}
		}
		
		private StudioCommerciale _studioCommerciale;
		public virtual StudioCommerciale StudioCommerciale
		{
			get
			{
				return this._studioCommerciale;
			}
			set
			{
				this._studioCommerciale = value;
			}
		}
		
	}
}
#pragma warning restore 1591
