#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class StudioCommerciale
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _denominazione;
		public virtual string Denominazione
		{
			get
			{
				return this._denominazione;
			}
			set
			{
				this._denominazione = value;
			}
		}
		
		private string _tipoSoftwareContabilita;
		public virtual string TipoSoftwareContabilita
		{
			get
			{
				return this._tipoSoftwareContabilita;
			}
			set
			{
				this._tipoSoftwareContabilita = value;
			}
		}
		
		private IList<Account> _accounts = new List<Account>();
		public virtual IList<Account> Accounts
		{
			get
			{
				return this._accounts;
			}
		}
		
		private IList<Azienda> _aziendas = new List<Azienda>();
		public virtual IList<Azienda> Aziendas
		{
			get
			{
				return this._aziendas;
			}
		}
		
		private IList<Nominativo> _nominativos = new List<Nominativo>();
		public virtual IList<Nominativo> Nominativos
		{
			get
			{
				return this._nominativos;
			}
		}
		
	}
}
#pragma warning restore 1591
